apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: observability
  description: Exposes host-level hardware and OS metrics as Prometheus metrics — CPU, memory, disk and network per node.

  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus-node-exporter
      targetRevision: 4.55.0
      helm:
        valueFiles:
          - $values/gitops-repo/observability/node-exporter/values/dev.yaml
    - repoURL: https://github.com/sleepymouse/gitops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
