apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: observability
  description: Distributed trace backend. Receives OTLP traces from Alloy and exposes a trace query API for Grafana. Enables service dependency mapping and trace-to-log correlation.

  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo-distributed
      targetRevision: 1.61.3
      helm:
        valueFiles:
          - $values/gitops-repo/observability/tempo/values/dev.yaml
    - repoURL: https://github.com/sleepymouse/gitops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
