apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: infrastructure

  source:
    repoURL: https://github.com/sleepymouse/gitops.git
    targetRevision: main
    path: gitops-repo/infrastructure/argocd/ingress/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
