apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: motd-ui-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sleepymouse/gitops.git
    targetRevision: main
    path: gitops-repo/charts/motd-ui
    helm:
      valueFiles:
        - ../../environments/dev/motd-ui-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: app-motd-ui-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
